language: node_js
node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    packages:
      - xvfb

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

install:
  - export CXX="g++-4.8"
  - npm install

after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage